CREATE TABLE IF NOT EXISTS `users` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `cpf` VARCHAR(20) NOT NULL UNIQUE,
    `email` VARCHAR(320) NOT NULL UNIQUE,
    `password` VARCHAR(128) NOT NULL,
    `balance` DECIMAL(19,2) NOT NULL,
    `type` ENUM('COMMON', 'MERCHANT') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;